global:
  nameOverride: logitech-media-server
bitwardenIds:
  logitech-media-server: OVERRIDE_NEEDED

app-template:
  controllers:
    logitech-media-server:
      annotations:
        reloader.stakater.com/auto: "true"
      containers:
        main:
          image:
            repository: toertel/logitech-media-server
            tag: v9.0.0-1@sha256:c904c54d8dd2fc9fc6b29df80f028ec1b215841eca86fb634bb7135b4e820841
          env:
            HTTP_PORT: 9000
            TZ: Etc/UTC
            SQUEEZE_VOL: /squeezebox
            SQUEEZE_UID: 1000
            SQUEEZE_GID: 1000
          #envFrom:
          #  - secretRef:
          #      name: logitech-media-server-secret
          probes:
            liveness:
              enabled: true
            readiness:
              enabled: true
          resources:
            requests:
              memory: 256Mi
            limits:
              memory: 4096Mi
          #securityContext:
          #  allowPrivilegeEscalation: false
          #  readOnlyRootFilesystem: true
          #  capabilities:
          #    drop:
          #      - ALL
      #pod:
      #  securityContext:
      #    runAsUser: 1000
      #    runAsGroup: 1000
      #    #runAsNonRoot: true
      #    fsGroup: 1000
      #    #fsGroupChangePolicy: OnRootMismatch
          #supplementalGroups:
          #  # Dialout on MicroOS
          #  - 492 
          #  - 20
  service:
    logitech-media-server:
      controller: logitech-media-server
      ports:
        http:
          port: 9000
        cli:
          enabled: true
          port: 9090
          protocol: TCP
          primary: true
        slimproto:
          enabled: true
          port: 3483
          protocol: TCP
        slimproto-udp:
          enabled: true
          port: 3483
          protocol: UDP

  persistence:
    config:
      existingClaim: lms-config
    playlists:
      existingClaim: lms-playlists
    music:
      existingClaim: lms-music
