---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: appset-base
spec:
  generators:
    # Generator for apps that should deploy to all cluster.
    - matrix:
        generators:
          - clusters: {}
          - list:
              elements:
                - appName: base
                  version: 1.0.75
                  namespace: default
                  ServerSideApply: "false"
                #- appName: monitoring-agent
                #  version: 1.0.7
                #  namespace: default
                #  ServerSideApply: "true"
  template:
    metadata:
      name: "{{ `{{appName}}` }}"
      annotations:
        argocd.argoproj.io/manifest-generate-paths: ".;.."
    spec:
      project: default
      sources:
        - repoURL: "{{ `{{ metadata.annotations.chart.repo }}` }}"
          chart: "{{ `{{appName}}` }}"
          targetRevision: "{{ `{{ version }}` }}"
          helm:
            parameters:
              - name: domain
                value: "{{ `{{ metadata.annotations.domain }}` }}"
              - name: clusterName
                value: "{{ `{{ metadata.annotations.clusterName }}` }}"
              - name: argo-cd.configs.cm.url
                value: "{{ `https://cluster.{{ metadata.annotations.clusterName }}.{{ metadata.annotations.domain }}` }}"
              - name: kube-prometheus-stack.prometheus.prometheusSpec.remoteWrite[0].name
                value: "storage"
              - name: kube-prometheus-stack.prometheus.prometheusSpec.remoteWrite[0].url
                value: "{{ `https://prometheus.{{ metadata.annotations.domain }}/api/v1/write` }}"
              #- name: autoUpdateK3s
              #  value: "true"
              #- name: proxy.middlewares.entrypoint
              #  value: "{ { $.Values.proxy.middlewares.entrypoint } }"
              ## Unset cert-manager-solver-token as it's not desired on remote.
              #- name: bitwardenIds.cert-manager-solver-token
              #  value: ""
            valueFiles:
              - values.yaml
              - $values/{{ `{{ metadata.annotations.values.path }}/{{ appName }}/{{ metadata.annotations.stage }}-values.yaml` }}
        - repoURL: "{{ `{{ metadata.annotations.values.repo }}` }}"
          targetRevision: main
          ref: values
      destination:
        name: "{{ `{{name}}` }}"
        namespace: "{{ `{{namespace}}` }}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          # Needed for: https://github.com/prometheus-community/helm-charts/issues/3345
          - ServerSideApply={{ `{{ServerSideApply}}` }}
