---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: pg-paperless
spec:
  instances: 1
  storage:
    size: 5Gi
    storageClass: local-path


  monitoring:
    enablePodMonitor: true

  postgresql:
    parameters:
      max_connections: "600"
      shared_buffers: 512MB

  # TODO:
  #backup:
  #  retentionPolicy: 7d
  #  barmanObjectStore:
  #    wal:
  #      compression: bzip2
  #      maxParallel: 8
  #    destinationPath: &dest s3://cloudnative-pg/
  #    endpointURL: &s3 https://${SECRET_CLOUDFLARE_ACCOUNT_ID}.r2.cloudflarestorage.com
  #    serverName: postgres16-v3
  #    s3Credentials: &credentials
  #      accessKeyId:
  #        name: *secretName
  #        key: s3-access-key-id
  #      secretAccessKey:
  #        name: *secretName
  #        key: s3-secret-access-key

  bootstrap:
    initdb:
      database: paperless
      owner: paperless
      secret:
        name: pg-paperless-secret

    # Use for major upgrades or creating new cluster from existing
    #  import:
    #    type: monolith
    #    databases: ["*"]
    #    roles: ["*"]
    #    source:
    #      externalCluster: old-cluster

    #recovery:
    #  # Should match name in externalClusters
    #  source: &backup postgres16-v2

  #externalClusters:
  #  - name: *backup
  #    barmanObjectStore:
  #      wal:
  #        compression: bzip2
  #        maxParallel: 8
  #      destinationPath: *dest
  #      endpointURL: *s3
  #      s3Credentials: *credentials
  # - name: old-cluster
  #   connectionParameters:
  #     host: postgres16-rw.default.svc.cluster.local
  #     user: postgres
  #     dbname: postgres
  #   password:
  #     name: postgres-creds
  #     key: password
#---
#apiVersion: postgresql.cnpg.io/v1
#kind: ScheduledBackup
#metadata:
#  name: postgres
#spec:
#  schedule: "@daily"
#  immediate: true
#  backupOwnerReference: self
#  cluster:
#    name: postgres16
