---
apiVersion: v1
kind: Service
metadata:
  name: proxy-service
  namespace: default
spec:
  type: ClusterIP
  ports:
    - port: 443
  selector:
    app.kubernetes.io/name: "sshd"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
    app.kubernetes.io/component: main
