apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: gitea-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-login
    kind: SecretStore
  target:
    name: gitea-secret
    creationPolicy: Owner
  data:
    - secretKey: bindDn
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: SecretStore
      remoteRef:
        key: {{ index .Values "bitwardenIds" "gitea" }}
        property: username
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: bindPassword
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: SecretStore
      remoteRef:
        key: {{ index .Values "bitwardenIds" "keycloak" }}
        property: password
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: key
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: SecretStore
      remoteRef:
        key: {{ index .Values "bitwardenIds" "gitea" }}
        property: oauth-key
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: secret
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: SecretStore
      remoteRef:
        key: {{ index .Values "bitwardenIds" "gitea" }}
        property: oauth-secret
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
