apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: gitea-admin-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-login
    kind: SecretStore
  target:
    name: gitea-admin-secret
    creationPolicy: Owner
  data:
  - secretKey: username
    remoteRef:
      key: {{ index .Values "bitwardenIds" "gitea-admin" }}
      property: username
      conversionStrategy: Default
      decodingStrategy: None
      metadataPolicy: None
  - secretKey: password
    remoteRef:
      key: {{ index .Values "bitwardenIds" "gitea-admin" }}
      property: password
      conversionStrategy: Default
      decodingStrategy: None
      metadataPolicy: None
